name: flutter_module_login
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # socket-io
#  adhara_socket_io: ^0.2.0
  # 消息订阅
  event_bus: ^1.1.0

  flutter_bloc: ^7.2.0

#  event_bus: 1.1.0

#  adhara_socket_io: ^0.4.2+1
#  adhara_socket_io: 0.1.10
  web_socket_channel: ^1.2.0
  flutter_common_plugin:
    path: ../flutter_common_plugin
#  adhara_socket_io:
#    path: dependencies/adhara_socket_io-0.1.10
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  path_provider_windows: 0.0.2
  path_provider_platform_interface: 1.0.3
  path_provider: 1.6.11


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
